### Introduction

In this notebook I will be using the LH and RH data in order to make any predictions/useful patterns that will tell us anything about individuals getting AD.

In [1]:
getwd()

[1] "/Users/andrescastellanos/Desktop/Summer_Research/AD_onboarding/R_analysis"

In [5]:
DXmerge_data <- read.csv("/Users/andrescastellanos/Desktop/Summer_Research/AD_onboarding/Data/dxmerge_rsfmri_baselinedata_2022_08_22.csv") 
LH_data <- read.delim("/Users/andrescastellanos/Desktop/Summer_Research/AD_onboarding/Data/aparc_stats_dkt_thickness_lh.txt")
RH_data <- read.delim("/Users/andrescastellanos/Desktop/Summer_Research/AD_onboarding/Data/aparc_stats_dkt_thickness_rh.txt")

In [6]:
head(DXmerge_data)
head(LH_data)
head(RH_data)

  PTID     scandate RID  SITEID E4_combine E4_3grp APOE4 PTGENDER PTDOBMM
1 002S0295 6/2/11    295 1      34         e4      P     M         6
2 002S0413 6/16/11   413 1      33         33      N     F        12
3 002S0685 7/8/11    685 1      33         33      N     F        11
4 002S0729 8/16/11   729 1      34         e4      P     F         5
5 002S1155 12/22/11 1155 1      33         33      N     M         1
6 002S1261 3/14/11  1261 1      33         33      N     F        12
  PTDOBYY ⋯ PTETHCAT     PTRACCAT VISCODE2 DX.EXAMDATE DX.new daydiff
1 1921    ⋯ Not Hispanic White    m60      6/2/11      CN       0
2 1929    ⋯ Not Hispanic White    m60      6/16/11     CN       0
3 1916    ⋯ Not Hispanic White    m60      7/5/11      CN      -3
4 1941    ⋯ Not Hispanic White    m60      8/2/11      Dement -14
5 1949    ⋯ Not Hispanic White    m60      1/9/12      MCI     18
6 1935    ⋯ Not Hispanic White    m48      3/17/11     CN       3
  mindaydiff ad_status ad_time Age_at_scan
1  0         No         343    90.0
2  0         No        2989    81.6
3  3         No         382    94.7
4 14         NA          NA    70.3
5 18         No        2699    63.0
6  3         No        2922    75.3

  lh.aparc.thickness    lh_bankssts_thickness
1 sub-002S0295X20110602 2.466
2 sub-002S0295X20120510 2.449
3 sub-002S0413X20060519 2.497
4 sub-002S0413X20061115 2.481
5 sub-002S0413X20070601 2.528
6 sub-002S0413X20080731 2.423
  lh_caudalanteriorcingulate_thickness lh_caudalmiddlefrontal_thickness
1 2.505                                2.579
2 2.399                                2.611
3 2.285                                2.372
4 2.164                                2.460
5 2.321                                2.466
6 2.238                                2.365
  lh_cuneus_thickness lh_entorhinal_thickness lh_fusiform_thickness
1 1.812               3.226                   2.689
2 1.839               3.306                   2.695
3 1.856               3.064                   2.570
4 1.898               3.040                   2.524
5 1.934               3.275                   2.603
6 1.881               3.217                   2.586
  lh_inferiorparietal_thickness lh_inferiortemporal_thickness
1 2.436                         2.559
2 2.469                         2.595
3 2.329                         2.575
4 2.339                         2.487
5 2.393                         2.634
6 2.323                         2.517
  lh_isthmuscingulate_thickness ⋯ lh_superiorparietal_thickness
1 2.139                         ⋯ 2.349
2 2.228                         ⋯ 2.353
3 1.938                         ⋯ 2.115
4 1.874                         ⋯ 2.148
5 1.927                         ⋯ 2.238
6 1.867                         ⋯ 2.159
  lh_superiortemporal_thickness lh_supramarginal_thickness
1 2.407                         2.470
2 2.424                         2.497
3 2.595                         2.339
4 2.497                         2.389
5 2.605                         2.442
6 2.554                         2.386
  lh_frontalpole_thickness lh_temporalpole_thickness
1 2.640                    3.648
2 2.615                    3.638
3 2.569                    3.499
4 2.323                    3.460
5 2.472                    3.500
6 2.459                    3.417
  lh_transversetemporal_thickness lh_insula_thickness
1 2.473                           2.864
2 2.469                           2.746
3 2.411                           2.892
4 2.460                           3.015
5 2.507                           2.931
6 2.429                           2.950
  lh_MeanThickness_thickness BrainSegVolNotVent eTIV
1 2.41423                    1077596            1597919
2 2.41708                    1062579            1597388
3 2.32936                    1042091            1475345
4 2.31502                    1020464            1464265
5 2.38548                    1041284            1488570
6 2.33981                    1016313            1471848

  rh.aparc.thickness    rh_bankssts_thickness
1 sub-002S0295X20110602 2.528
2 sub-002S0295X20120510 2.491
3 sub-002S0413X20060519 2.484
4 sub-002S0413X20061115 2.536
5 sub-002S0413X20070601 2.591
6 sub-002S0413X20080731 2.551
  rh_caudalanteriorcingulate_thickness rh_caudalmiddlefrontal_thickness
1 2.353                                2.577
2 2.252                                2.539
3 2.393                                2.327
4 2.206                                2.211
5 2.360                                2.456
6 2.451                                2.353
  rh_cuneus_thickness rh_entorhinal_thickness rh_fusiform_thickness
1 1.797               3.244                   2.622
2 1.764               3.382                   2.532
3 1.850               3.446                   2.551
4 1.896               3.369                   2.572
5 1.958               3.261                   2.569
6 1.909               3.355                   2.581
  rh_inferiorparietal_thickness rh_inferiortemporal_thickness
1 2.336                         2.549
2 2.306                         2.477
3 2.264                         2.596
4 2.262                         2.645
5 2.338                         2.678
6 2.293                         2.669
  rh_isthmuscingulate_thickness ⋯ rh_superiorparietal_thickness
1 2.369                         ⋯ 2.292
2 2.225                         ⋯ 2.258
3 2.188                         ⋯ 2.077
4 2.182                         ⋯ 2.071
5 2.273                         ⋯ 2.147
6 2.323                         ⋯ 2.105
  rh_superiortemporal_thickness rh_supramarginal_thickness
1 2.667                         2.433
2 2.591                         2.495
3 2.536                         2.360
4 2.495                         2.374
5 2.640                         2.457
6 2.583                         2.360
  rh_frontalpole_thickness rh_temporalpole_thickness
1 2.597                    3.454
2 2.621                    3.348
3 2.569                    3.331
4 2.496                    3.509
5 2.506                    3.477
6 2.471                    3.461
  rh_transversetemporal_thickness rh_insula_thickness
1 2.143                           2.684
2 2.107                           2.660
3 2.478                           2.774
4 2.413                           2.926
5 2.585                           2.909
6 2.511                           2.884
  rh_MeanThickness_thickness BrainSegVolNotVent eTIV
1 2.38452                    1077596            1597919
2 2.35337                    1062579            1597388
3 2.32349                    1042091            1475345
4 2.29443                    1020464            1464265
5 2.38515                    1041284            1488570
6 2.34735                    1016313            1471848